[gcp_service_account]
type = "service_account"
project_id = "crafty-calling-463904-m8"
private_key_id = "294dc2eb52a3c9341995293ca901c467dacb1b37"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDf54R0ikR09g20
9xHfamlOEPGHrrmWHGQ0RGL5kkDUvdtBuVtzXcmF4/5MXTo7bW+BOHdN3lamljXH
ya+8OHrEQ/tHpfaYQnKjjMpv3icf8OYqVSFIzoSwJZzah2+3ymDZptl5Jsb4q2yE
coeWY0fxU9a1I4zFqYE5yTN40HpqegpTJiJXY6uXj2P4fC2SMDTy1/5Z9gGmQNnh
B4KuasjSA3pNc9CudCh5HBxlh/FxeFT6Ujj/V06ktPicluIcuDKD1TakpDNj/Glc
PZhIeOy0+0c+7QI63cQqzHAehW7wMZYzImFRSwGuxJaIM/PBxJnnudf/dn/jkDkv
kXLjav7jAgMBAAECggEAYMHqwnXx6V1fRQG0Doksopi913WRK6ZvQwr+fn1OWOEG
vBs+wtcXvC1vek6bWI0NL5lYLSVU6r5k1UZ6E+uQWfpKv4afzuKAKd8wqDEnVS1E
Oaz6Kj1cp8ZJR0JZ6+GgAs6QkkNInrNtvLrFjx6uO0KQuUx4i/6ZIoCpJp9pF1OA
7dGQyI8tbenLJhwfmtqQ9d5a5QlITogvQCzanNf4+6bEwvePC+llNKo/IEVuEiLI
goCA8VDhb9MEVZbfrCO62YcejRR0WJRycKiECnE/IRXGOCQDGazgHUKr/8aMgRo2
MSMLrovgOE9bdMzm6zg6hIFLxuj+WLlq/xyNJZIZ2QKBgQDxvSQh3Suvx2GaKu7W
PNdHXWf1C8cL3rEdgoZrgnzxwMg+yFaxnFp4I79uAqOeZkzpy1aAI32F1yeRaRck
Tn/G/EcU8OPJh6ANcUBuJYGZLcB2uCsQJQxA1ghq+gYXnGWsP2RxiXY5BI9Nq+iy
NVsq3m10eU7FI732G7d1byy7ZQKBgQDtHQgGjPdmAVdZoIHWN52lXYuUvbLkwFWt
xs6V8xN40+S23NYpzhgfu3uwCSnZ3h6Rb1n8+uSdmRyXlSp9dtWjsmtkp2drID9M
OZE9Kh9iCtCOQGTnFloZAF5Mnukm3LUPXxJUGgUVIpQN0urDyyt9grJpeFF2FwG/
Y6dneV3ApwKBgQDpi+ZgoSEXzfTJ0Ti12knSNLe+0wYWvas362aab5LurWXI4hx/
s6Lj9wV27y3MVuFv7nc/jQo0SE19+p3VAdIJGKpD3Qb1KQbEdendgHbY2o7bI8rW
6jQQX7f6Qluoa/z+kLAl0LxbEcCxNai2oz3VCNeOc7RaWdGo99Yiqqn40QKBgAow
NSgS5o57gEVZoDqUKTHx0w2RGR67JPNSl43Z4/xNHoa89nbVZDP42le2DRZPdQDK
yBMWtLwQ2CmrPygk8wkVoYexqb/wosejsZnvNWoBDPUPz0Yer8BjQ6oHKf2BfkYq
z57Nf2ppEfOGHJBNKpE6DHB7uwRX+LtAjPDlRiIBAoGAR6NX5bpNT6MvRkMFL/Ua
1ccGNgWQfWBa6xwfDKTbHvxGW2h42tIKAoiX/p3YUAj3O04KqZ86Vo04WJEjqxRB
m+37iXpcJBAocufuw4UXoYnHrf2G9uyQxE9YnYV9hg2suzqUt51NeyHZXHYMeaCd
XeHg7JBt8FVJWFPnuJmIv60=
-----END PRIVATE KEY-----
"""
client_email = "streamlit-todo-bot@crafty-calling-463904-m8.iam.gserviceaccount.com"
client_id = "103020774387147915625"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-todo-bot%40crafty-calling-463904-m8.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
